# Generated by Django 4.1.6 on 2023-02-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AqApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pollutant',
            fields=[
                ('pollutant_id', models.AutoField(primary_key=True, serialize=False)),
                ('pollutant_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PollutantProperty',
            fields=[
                ('prop_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_id', models.IntegerField()),
                ('aqi', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='site',
            old_name='stId',
            new_name='station_id',
        ),
        migrations.AddField(
            model_name='site',
            name='station_type',
            field=models.CharField(default='', max_length=50, verbose_name=(('1', 'GROUND'), ('2', 'STATION'), ('3', 'BKK'))),
            preserve_default=False,
        ),
    ]
