# Generated by Django 4.1.6 on 2023-03-09 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AqApp', '0003_locationdata_polluantdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdata',
            name='Pollutant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AqApp.pollutant'),
        ),
        migrations.AddField(
            model_name='locationdata',
            name='max_aqi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationdata',
            name='min_aqi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
