# Generated by Django 4.1.6 on 2023-03-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AqApp', '0006_rename_pollutant_locationdata_pollutant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polluantdata',
            options={'verbose_name': 'Pollutant Data'},
        ),
        migrations.AddField(
            model_name='locationdata',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='polluantdata',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
