# Generated by Django 4.1.6 on 2023-03-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AqApp', '0007_alter_polluantdata_options_locationdata_enable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationdata',
            old_name='enable',
            new_name='enabled',
        ),
        migrations.RenameField(
            model_name='polluantdata',
            old_name='enable',
            new_name='enabled',
        ),
    ]
