# Generated by Django 4.1.6 on 2023-03-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AqApp', '0008_rename_enable_locationdata_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationdata',
            options={'verbose_name': 'Location'},
        ),
        migrations.AlterModelOptions(
            name='polluantdata',
            options={'verbose_name': 'Pollutant'},
        ),
        migrations.AlterField(
            model_name='locationdata',
            name='latitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='locationdata',
            name='longitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
