# Generated by Django 3.2.18 on 2023-03-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AqApp', '0010_alter_locationdata_max_aqi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationdata',
            name='max_aqi',
        ),
        migrations.RemoveField(
            model_name='locationdata',
            name='min_aqi',
        ),
        migrations.AddField(
            model_name='locationdata',
            name='StId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationdata',
            name='saved_location',
            field=models.BooleanField(default=True),
        ),
    ]
