# Generated by Django 4.1.6 on 2023-03-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AqApp', '0011_auto_20230325_1336'),
    ]

    def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
        Location = apps.get_model('AqApp', 'LocationData')
        Location.objects.filter(source="AIR NOW").update(source="AIRNOW")
        Location.objects.filter(source="AERO NET").update(source="AERONET")

    operations = [
        migrations.AlterField(
            model_name='locationdata',
            name='source',
            field=models.CharField(choices=[('AIRNOW', 'AIRNOW'), ('AERONET', 'AERONET')], default='AIRNOW', max_length=26),
        ),
        migrations.RunPython(combine_names),
    ]
